### ISSUE TITLE
Allow manual padding disable

### ISSUE THREAD

**Issue by vasco-santos** [LinusU/base32-encode#2]
As specified by [RFC4648](https://tools.ietf.org/html/rfc4648#section-3.2), the padding symbol is not mandatory. 

I am currently using your module and I need to disable the padding, in order to be coherent among other languages.

Sources:

https://godoc.org/encoding/base64#pkg-variables
https://github.com/golang/go/blob/244c98fe01b2af844f6f41b7123a17b7b56f1c2a/src/encoding/base64/base64.go#L105

**Comment by LinusU** [comment]
Sounds reasonable 👍 

Any ideas for option name? Maybe `{ disablePadding: true }`, or just `{ padding: false }`... or `{ stripPadding: true }` 🤔

**Comment by vasco-santos** [comment]
At first, when I created this PR I was thinking about `{ padding: false }`, but I prefer `padding` to be the variable that you already use. So, I was thinking on something more similar to what is being called in GO, such as `{ rawEncoding: true }`. What do you think?

I can create the PR later or tomorrow with this 😄

**Comment by LinusU** [comment]
How about something like this?

```diff
-module.exports = function base32Encode (buffer, variant) {
+module.exports = function base32Encode (buffer, variant, options) {
+  options = options || {}
+
-  var alphabet, padding
+  var alphabet, defaultPadding
 
   switch (variant) {
     case 'RFC3548':
     case 'RFC4648':
       alphabet = RFC4648
-      padding = true
+      defaultPadding = true
       break
     case 'RFC4648-HEX':
       alphabet = RFC4648_HEX
-      padding = true
+      defaultPadding = true
       break
     case 'Crockford':
       alphabet = CROCKFORD
-      padding = false
+      defaultPadding = false
       break
     default:
       throw new Error('Unknown base32 variant: ' + variant)
   }

+  var padding = (options.padding === undefined ? defaultPadding : options.padding)
   var length = buffer.byteLength
   var view = new Uint8Array(buffer)
```

Would love a PR 🙌

**Comment by vasco-santos** [comment]
SGTM! I will try to do it later
