### ISSUE TITLE
ArrayBuffer concerns and feature request

### ISSUE THREAD

**Issue by dlongley** [LinusU/base32-encode#5]
Hi, we're using this library to encode bytes to a character set that works well with QR codes. We noticed that the input to your API is an `ArrayBuffer` rather than a view on that `ArrayBuffer`, such as a `Uint8Array`. 

If a view were accepted instead, we wouldn't have to worry about corner cases where the underlying `ArrayBuffer` isn't the same size as the view. If a `Uint8Array`, `x`, is a view on an `ArrayBuffer` that is larger than the `Uint8Array`, then passing the `x.buffer` to the API in this library would result in it encoding outside of the view. This requires the caller to check that the underlying `ArrayBuffer` is the same size, and if not, create a new `ArrayBuffer` made by copying the data within the view.

Could your API and documentation be adjusted to accept views -- or, at least minimally, a `Uint8Array` view as it is likely the most common? Looking at the code, a `Uint8Array` is internally used to wrap the `ArrayBuffer` parameter. My understanding is that this wouldn't need to change if the input were a `Uint8Array` as opposed to an `ArrayBuffer`.

I'll be filing a similar issue on https://github.com/LinusU/base32-decode -- where the return value is an `ArrayBuffer` instead of a view on one.

Related: https://github.com/digitalbazaar/vpqr/issues/2

**Comment by dlongley** [comment]
Aside: So I had planned on filing an issue on https://github.com/LinusU/base32-decode as well, but *as currently implemented*, there is no danger that the `ArrayBuffer` returned in its API would have any size other than the `Uint8Array` that is created internally. The ECMAScript spec indicates that the `ArrayBuffer` size will match the length of the `Uint8Array` that is created there based on how it is constructed:

https://tc39.es/ecma262/#sec-typedarray
https://tc39.es/ecma262/#sec-allocatetypedarray
https://tc39.es/ecma262/#sec-allocatetypedarraybuffer

I still think it's cleaner to return a view (such as `Uint8Array`) in the decoding API, however, as it would be a breaking change on that library I won't file an issue.

It's still important, IMO, for the encoder side of things to accept a view as it otherwise places an undo burden on the caller to ensure that the `ArrayBuffer` size matches the view they are most likely working with and want encoded.

**Comment by LinusU** [comment]
Sounds good, fixed in [🚢 1.2.0 / 2021-03-30](https://github.com/LinusU/base32-encode/releases/tag/v1.2.0)

If you want to open an issue on the decoder we could discuss that there as well, but I'm a bit hesitant there since you can always go from ArrayBuffer -> Uint8ArrayView in one call, but doing `.buffer` on a returned view doesn't necessarily return a buffer that _just_ contains that data (even though it always would on the view returned from that library)

**Comment by dlongley** [comment]
@LinusU -- Thank you for the quick response! Also, I think the decode lib is ok as-is. Have a nice day! :)
